# Lab Practice: Epidemiological Analysis of the Broad Street Outbreak


### Background
In this lab, you are acting as a researcher in Dr. John Snow’s lab. You have been provided with a preliminary dataset of cholera deaths from the 1854 outbreak. 

### GitHub Practice Goals:
1. **Branching:** You should be working on a branch named `feature-outlier-check`.
2. **Analysis:** Complete the tasks below using Pandas.
3. **Collaboration:** Once finished, you will Push your changes and submit a Pull Request.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Standard plot styling

In [2]:
# Load the dataset
# Ensure cholera_deaths.csv is in the same folder as this notebook
df = pd.read_csv('/Users/anya/Desktop/cholera_deaths.csv')

# Initial peek at the data
df.head()

   Death_ID        Street  Age Gender
0       101     Oxford St   14      M
1       102     Oxford St   26      F
2       103      Broad St   20      M
3       104     Oxford St   18      F
4       105  Cambridge St   27      F

### Task 1: Data Inspection
Before analyzing, we need to know the shape and quality of our data. 

**TODO:** Write code to display the total number of rows and columns, and check for any missing values.

In [7]:
df.info()

#There are 4 columns and 20 rows, with no missing values.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Death_ID  20 non-null     int64
 1   Street    20 non-null     object
 2   Age       20 non-null     int64
 3   Gender    20 non-null     object
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

### Task 2: Identifying the Final Record
In clinical data tracking, the highest ID often represents the most recently reported case.

**TODO (GitHub Simulation Task):** Find and display the row for the patient with the highest `Death_ID`.

In [13]:
#df.describe() --> How I found the max death_ID
df[df['Death_ID'] == 120]

    Death_ID    Street  Age Gender
19       120  Broad St   49      F

### Task 3: Age Distribution
Dr. Snow needs to know if the outbreak is affecting a specific age group.

**TODO:** Calculate the mean, median, and standard deviation of the 'Age' column.

In [35]:
print('Age mean:',df['Age'].mean())
print('Age median:',df['Age'].median())
print('Age standard deviation:',df['Age'].std())

Age mean: 36.3
Age median: 27.5
Age standard deviation: 20.996490934890698

## Stop & Submit
Once you have completed the tasks above, follow these steps to submit your work via GitHub:

1. **Save** this notebook.
2. **Commit** your changes in GitHub Desktop (Message: `Complete outlier check and age stats`).
3. **Push** your branch (`feature-outlier-check`) to your Fork.
4. Go to the original Class Repository on GitHub and click **"Compare & pull request"**.
5. In your PR description, write: *"Added logic to identify the most recent death record and calculated age statistics for the cohort."*

In [ ]:
#commit